### ISSUE TITLE
[Bug] Connection drops for bots

### ISSUE THREAD

**Issue by mugman174** [fosscord/fosscord-gateway#61]
**Is your feature request related to a problem? Please describe.**
When I tried to connect to my local instance on localhost, I see requests to `ws://localhost:3001/?encoding=json&v=8&compress=zlib-stream` but there is no response, so it doesn't go past the loading screen.

**Describe the solution you'd like**
I would like for a web-socket to be added so the client can connect and do whatever it does with the server.

**Describe alternatives you've considered**
I made manual requests following the [Discord docs](https://discord.com/developers/docs/), which worked. However, that is not a very user-friendly way of using Fosscord and is very tedious. I am currently trying to interface with discord.py.

<small>Note: I am not using discord (discord.com/api) to do this, I am running a server on localhost. If I am breaking the Discord TOS in any way, notify me so I will know and can stop.</small>

**Comment by samuelscheit** [comment]
there is no official bot support yet
